package pe.com.compartamos.tarifario;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class beanResponse implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer contador;
   private java.lang.String tipoCambioMax;
   private java.lang.String tipoCambioMin;

   public beanResponse()
   {
   }

   public java.lang.Integer getContador()
   {
      return this.contador;
   }

   public void setContador(java.lang.Integer contador)
   {
      this.contador = contador;
   }

   public java.lang.String getTipoCambioMax()
   {
      return this.tipoCambioMax;
   }

   public void setTipoCambioMax(java.lang.String tipoCambioMax)
   {
      this.tipoCambioMax = tipoCambioMax;
   }

   public java.lang.String getTipoCambioMin()
   {
      return this.tipoCambioMin;
   }

   public void setTipoCambioMin(java.lang.String tipoCambioMin)
   {
      this.tipoCambioMin = tipoCambioMin;
   }

   public beanResponse(java.lang.Integer contador,
         java.lang.String tipoCambioMax, java.lang.String tipoCambioMin)
   {
      this.contador = contador;
      this.tipoCambioMax = tipoCambioMax;
      this.tipoCambioMin = tipoCambioMin;
   }
   
      public beanResponse(java.lang.String tipoCambioMin)
   {
      this.tipoCambioMin = tipoCambioMin;
   }

}