package pe.com.compartamos.tarifario;

import pe.com.compartamos.tarifario.beanRequest;

global java.lang.Integer myGlobal;
global String diario;
global java.lang.Integer x;

rule "Setting test"


    dialect "mvel"
    ruleflow-group "carga-inicial"
    no-loop true
    
    when
        request : beanRequest()
        
    then
    
        //x = 3;
        myGlobal = 0;
        drools.getKnowledgeRuntime().setGlobal("myGlobal",myGlobal);
        //drools.getKnowledgeRuntime().setGlobal("x",Integer.valueOf(x));
        
        System.out.println("Rule fired : [" + drools.getRule().getName() + "]");

end


